apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mar12-finalragtest
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/mar12-finalragtest:1df2005b34950bf1c19a56a26ab334786f59aea8@sha256:a889f660208efffeaa22cbf14a585a3d331b1d62dadfcbe1a56a69711bc6e9e1 # use pre-built to bootstrap
          name: app-inference
