apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: mar12-finalragtest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar12-finalragtest
  name: mar12-finalragtest
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
