apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mar12-finalragtest-database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar12-finalragtest-database
  name: mar12-finalragtest-database
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/instance: mar12-finalragtest-database
