apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mar12-finalragtest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar12-finalragtest
  name: mar12-finalragtest
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: mar12-finalragtest
